const KEY='worklog-data-v1',today=new Date();let selectedWeek=new Date(today),selectedDate='',adjustmentType='leave-full',data={entries:{},adjustments:{},goal:40,company:'',theme:'sage',name:'Andrew'};selectedWeek.setHours(0,0,0,0);
try{const stored=localStorage.getItem(KEY);if(stored){const parsed=JSON.parse(stored);data={...data,...parsed,entries:parsed.entries||{},adjustments:parsed.adjustments||{}}}}catch{localStorage.removeItem(KEY)}
const $=s=>document.querySelector(s),escapeHtml=value=>String(value).replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char])),fmt=d=>{const v=new Date(d);return `${v.getFullYear()}-${String(v.getMonth()+1).padStart(2,'0')}-${String(v.getDate()).padStart(2,'0')}`},dateObj=s=>new Date(`${s}T12:00:00`),save=()=>{localStorage.setItem(KEY,JSON.stringify(data));pushToCloud()};selectedDate=fmt(today);
function monday(d){const v=new Date(d),day=v.getDay()||7;v.setDate(v.getDate()-day+1);v.setHours(0,0,0,0);return v}
function weekDates(){const start=monday(selectedWeek);return Array.from({length:5},(_,i)=>{const d=new Date(start);d.setDate(start.getDate()+i);return d})}
function hoursForEntry(e){if(!e?.in||!e?.out)return 0;const[a,b]=e.in.split(':').map(Number),[c,d]=e.out.split(':').map(Number);let minutes=c*60+d-(a*60+b);if(minutes<0)minutes+=1440;return minutes/60}
function adjustmentHours(d){return data.adjustments[d]?.hours||0}function weekTotal(){return weekDates().reduce((sum,d)=>sum+hoursForEntry(data.entries[fmt(d)])+adjustmentHours(fmt(d)),0)}function hm(h){const m=Math.round(Math.max(0,h)*60);return `${Math.floor(m/60)}h ${String(m%60).padStart(2,'0')}m`}function currentTime(){const d=new Date();return `${String(d.getHours()).padStart(2,'0')}:${String(d.getMinutes()).padStart(2,'0')}`}
function updateClockButton(){const e=data.entries[fmt(today)]||{},open=Boolean(e.in&&!e.out);$('#clockButton').classList.toggle('clock-out',open);$('#clockButtonLabel').textContent=open?'Clock out':'Clock in';$('#clockButtonHint').textContent=open?`Started at ${e.in} · tap when you finish`:'Tap to start your workday'}
function updateProfile(){const name=(data.name||'Andrew').trim()||'Andrew';$('#userName').textContent=`${name}.`;$('#avatar').textContent=name.charAt(0).toUpperCase()}
function changeWeeks(delta){if(!delta)return;selectedWeek.setDate(selectedWeek.getDate()+delta*7);render();const c=$('#weekContent');c.classList.remove('slide-from-right','slide-from-left');void c.offsetWidth;c.classList.add(delta>0?'slide-from-right':'slide-from-left')}
function render(){const dates=weekDates(),total=weekTotal(),goal=data.goal||40,complete=Math.min(total/goal,1),remaining=Math.max(0,goal-total);$('#todayLabel').textContent=new Intl.DateTimeFormat('en',{weekday:'long',day:'numeric',month:'long'}).format(today).toUpperCase();$('#weekTitle').textContent=`${new Intl.DateTimeFormat('en',{month:'short',day:'numeric'}).format(dates[0])} — ${new Intl.DateTimeFormat('en',{month:'short',day:'numeric'}).format(dates[4])}`;$('#weekRange').textContent=dates[0].getFullYear();$('#hoursDone').textContent=hm(total);$('#hoursGoal').textContent=hm(goal);$('#hoursRemaining').textContent=remaining?hm(remaining):'All done';$('#remainingBar').style.width=`${Math.min(100,complete*100)}%`;$('#progressRing').style.background=`conic-gradient(var(--green) ${complete*360}deg, var(--surface-2) 0deg)`;$('#progressCaption').textContent=total?`${Math.round(complete*100)}% of your weekly goal complete.`:'Log your first day to get started.';$('#weekStatus').textContent=total>=goal?'COMPLETE':total>=goal*.75?'ON TRACK':'IN PROGRESS';
const logged=dates.filter(d=>hoursForEntry(data.entries[fmt(d)])+adjustmentHours(fmt(d))>0).length;$('#daysLogged').innerHTML=`${logged} <small>/ 5</small>`;$('#dayDots').innerHTML=dates.map(d=>`<i class="${hoursForEntry(data.entries[fmt(d)])+adjustmentHours(fmt(d))?'done':''}"></i>`).join('');$('#dayList').innerHTML=dates.map(d=>{const key=fmt(d),e=data.entries[key],a=data.adjustments[key],hours=hoursForEntry(e)+adjustmentHours(key),description=a?`<span class="adjustment-badge">${a.type==='holiday'?'PUBLIC HOLIDAY':a.hours===4?'HALF DAY':'LEAVE'} · ${hm(a.hours)}</span>`:e?`<strong>${e.out?hm(hours):'Clocked in'}</strong> · ${escapeHtml(e.company||data.company||'Work')}`:'Not logged';return `<div class="day-row"><div class="day-name">${new Intl.DateTimeFormat('en',{weekday:'short'}).format(d)}<span>${new Intl.DateTimeFormat('en',{day:'numeric',month:'short'}).format(d)}</span></div><div class="day-desc">${description}</div><button class="day-action ${e||a?'':'log'}" data-day="${key}">${a&&!e?'Adjust':'Edit'}</button></div>`}).join('');document.querySelectorAll('[data-day]').forEach(b=>b.onclick=()=>openEntry(b.dataset.day));updateClockButton();renderHistory()}
function openEntry(d){selectedDate=d;const e=data.entries[d]||{};$('#modalDate').textContent=new Intl.DateTimeFormat('en',{weekday:'long',day:'numeric',month:'long'}).format(dateObj(d));$('#clockIn').value=e.in||'09:00';$('#clockOut').value=e.out||'17:00';$('#entryCompany').value=e.company||data.company||'';$('#entryNote').value=e.note||'';$('#deleteEntry').style.display=data.entries[d]?'block':'none';$('#entryModal').hidden=false}
function renderHistory(){const keys=[...new Set([...Object.keys(data.entries),...Object.keys(data.adjustments)])].sort().reverse(),total=keys.reduce((sum,k)=>sum+hoursForEntry(data.entries[k])+adjustmentHours(k),0);$('#historyStats').innerHTML=`<div class="card"><span class="card-label">TOTAL HOURS</span><strong>${hm(total)}</strong></div><div class="card"><span class="card-label">DAYS LOGGED</span><strong>${keys.length}</strong></div><div class="card"><span class="card-label">WEEKS</span><strong>${new Set(keys.map(k=>fmt(monday(dateObj(k))))).size}</strong></div>`;$('#historyList').innerHTML=keys.length?keys.map(k=>{const e=data.entries[k],a=data.adjustments[k],label=a?(a.type==='holiday'?'Public holiday':a.hours===4?'Half-day leave':'Leave'):(e?.company||data.company||'Work');return `<div class="history-item"><div><strong>${new Intl.DateTimeFormat('en',{weekday:'short',day:'numeric',month:'short',year:'numeric'}).format(dateObj(k))}</strong><p class="muted">${escapeHtml(label)}${e?.in?` · ${e.in}–${e.out||'…'}`:''}</p></div><strong class="history-hours">${hm(hoursForEntry(e)+adjustmentHours(k))}</strong></div>`}).join(''):'<div class="empty-state">Your history will appear here once you log a day.</div>'}
function closeModal(id){$(id).hidden=true}
document.addEventListener('click',e=>{const close=e.target.closest('[data-close]');if(close)closeModal('#'+close.dataset.close);const now=e.target.closest('[data-now]');if(now)$('#'+now.dataset.now).value=currentTime();const choice=e.target.closest('[data-adjustment]');if(choice){adjustmentType=choice.dataset.adjustment;document.querySelectorAll('.choice').forEach(x=>x.classList.toggle('active',x===choice))}});
$('#clockButton').onclick=e=>{e.preventDefault();const key=fmt(today),entry=data.entries[key]||{};data.entries[key]=entry.in&&!entry.out?{...entry,out:currentTime(),company:entry.company||data.company||''}:{...entry,in:currentTime(),out:'',company:entry.company||data.company||''};save();render()};
$('#saveEntry').onclick=()=>{data.entries[selectedDate]={in:$('#clockIn').value,out:$('#clockOut').value,company:$('#entryCompany').value,note:$('#entryNote').value};save();closeModal('#entryModal');render()};$('#deleteEntry').onclick=()=>{delete data.entries[selectedDate];save();closeModal('#entryModal');render()};$('#addAdjustment').onclick=()=>{$('#adjustmentDate').value=selectedDate;$('#adjustmentModal').hidden=false};$('#saveAdjustment').onclick=()=>{const d=$('#adjustmentDate').value;if(!d)return;data.adjustments[d]={hours:adjustmentType==='leave-half'?4:8,type:adjustmentType==='holiday'?'holiday':'leave',label:$('#adjustmentLabel').value};save();closeModal('#adjustmentModal');render()};
let swipeStartX=0;$('#weekSwipeArea').addEventListener('touchstart',e=>{swipeStartX=e.changedTouches[0].screenX},{passive:true});$('#weekSwipeArea').addEventListener('touchend',e=>{const distance=e.changedTouches[0].screenX-swipeStartX;if(Math.abs(distance)>45)changeWeeks(distance<0?1:-1)},{passive:true});document.querySelectorAll('.nav-item').forEach(item=>item.onclick=()=>{document.querySelectorAll('.nav-item').forEach(nav=>nav.classList.toggle('active',nav===item));document.querySelectorAll('.view').forEach(view=>view.classList.toggle('active-view',view.id===item.dataset.view));if(item.dataset.view==='history')renderHistory()});
function applyTheme(){const theme=data.theme||'sage';document.body.dataset.theme=theme;document.querySelectorAll('[data-theme-choice]').forEach(button=>button.classList.toggle('active',button.dataset.themeChoice===theme))}document.querySelectorAll('[data-theme-choice]').forEach(button=>button.onclick=()=>{data.theme=button.dataset.themeChoice;save();applyTheme();render()});$('#nameInput').value=data.name||'';$('#goalInput').value=data.goal;$('#companyInput').value=data.company;$('#saveSettings').onclick=()=>{data.name=$('#nameInput').value.trim();data.goal=Number($('#goalInput').value)||40;data.company=$('#companyInput').value;save();updateProfile();render()};applyTheme();updateProfile();render();

// ---- Cloud sync (Supabase) ----
const SUPABASE_URL='https://hlfevzfwrzjkahalohsc.supabase.co',SUPABASE_KEY='sb_publishable_5B9LeRXRHS7I0j-nf63zaA_zCU6FfhC';
const sb=window.supabase?window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY):null;
let cloudUserId=null,syncTimer=null;
function setSyncLabel(text){const el=$('#syncLabel');if(el)el.textContent=text}
function pushToCloud(){if(!sb||!cloudUserId)return;clearTimeout(syncTimer);syncTimer=setTimeout(async()=>{setSyncLabel('Syncing…');try{const{error}=await sb.from('worklog_data').upsert({user_id:cloudUserId,payload:data,updated_at:new Date().toISOString()});if(error)throw error;setSyncLabel('Synced to cloud')}catch(err){console.error('Cloud sync failed:',err);setSyncLabel('Saved locally (offline)')}},600)}
async function initCloudSync(){
  if(!sb){setSyncLabel('Saved locally');return}
  setSyncLabel('Connecting…');
  try{
    let{data:{session}}=await sb.auth.getSession();
    if(!session){const{data:signInData,error:signInError}=await sb.auth.signInAnonymously();if(signInError)throw signInError;session=signInData.session}
    cloudUserId=session.user.id;
    const{data:row,error}=await sb.from('worklog_data').select('payload').eq('user_id',cloudUserId).maybeSingle();
    if(error)throw error;
    if(row&&row.payload){
      data={...data,...row.payload,entries:row.payload.entries||{},adjustments:row.payload.adjustments||{}};
      localStorage.setItem(KEY,JSON.stringify(data));
      updateProfile();applyTheme();render();
      setSyncLabel('Synced to cloud')
    }else{
      pushToCloud()
    }
  }catch(err){
    console.error('Cloud sync unavailable:',err);
    setSyncLabel('Saved locally (offline)')
  }
}
initCloudSync();
